language: java

notifications:
  webhooks:
    urls:
      secure: WFnmxJEFjfXwydf6Fdsfup0lqE1jc8yNRRhhUhM1V2kaoQWfQ50ri3lpKpXURAw2F6zjQPB414+cOLqsXEMhHQRoluQvWfxY1dfU0MXSVmTla46XXcqEQqtrOwmtD96qlvg7shrtdLsd82IL1Nrt+6K7kVArzwSVgYo2qtVCaurWMbUUeyzzEr337rRCkrS6tZLYitNRomqRTj6hV4VpVWIbuhEzZrXs1HD5kb0J+NnbXMhLF3VMGstI6rP1yyUHMoUyXIKr+DMi3yE5tn2jQ0Bj1Z8P4PV/YmkSPQTx3ipnuFqJYvH5xCZsrllm6RQnnlQNNleAr0uQdhI7UythUICKTN/hIuGsRnSCivkXv1neyT7cblrrPcHd7CT1AQpkVALzlsFtroMyOnWp2qTdk8GDnP4uMlRsd9fhnHa0p7XBFniNe/Wt43sDiC6qLCZirZ2Xu2TtVfalSwv0m0kSdRzkeqv5lce7WA7Hgaa2p9ZtE8quJWsGp8O17tkhaMv4kBBmCLcQkhjfrwFQF4nxYlUjHTk0vxsV+P1C7XDIlNxxHBZMEFrahEZQnNJyONzDYwnhCWH1xQuhkmk0aR2dvupDfEA5+sdesESvZlRpiM48AFiIDFHU7FkqwbKao2M3X17C8yDACVf6EUlu7kjWWqQfHjgMEcfeivn1fE6/4dI=
